config/routes.rb
Rails.application.routes.draw do
  get "home"=> 'home#index'

  resources :employees


  get "about" =>'pages#about_us'
  get "contact"=>'pages#contact_us'
  get "pages1"=>'pages#pages1'
  root 'home#index'
  get "empnew" => 'employees#new'
  get "empindex" => 'employee#index'





end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :employee
end

app/models/employee.rb
class Employee < ApplicationRecord
  has_many :documents
  
  validates :first_name, :last_name, presence: true
  validates :email, presence: true, uniqueness:true
  validates :city, :state ,:country, presence:true

  def name
    "#{first_name} #{last_name}".strip.capitalize
  end

  def address
    "#{city}, #{state}, #{country}".strip.capitalize
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/employees_controller.rb
class EmployeesController < ApplicationController
  def index
    @employees = Employee.all
  end
  def new
    @employee = Employee.new
  end

  def create
    # @employee = Employee.new(first_name: params[:employee][:first_name],
    # last_name: params[:employee][:last_name],
    # email:params[:employee][:email],
    # city: params[:employee][:city],
    # state: params[:employee][:state],
    # country: params[:employee][:country]
    # )
    @employee = Employee.new(employee_params)
    if @employee.save
      redirect_to employees_path, notice:"Employee has been created"
    else
      render :new
    end
  end

  def edit
    @employee = Employee.find(params[:id])
  end
  def update
    @employee = Employee.find(params[:id])
    if @employee.update(employee_params)
      redirect_to employees_path, notice:"Employee has been updated"
    else
      render :edit
    end
  end
  def show
    @employee = Employee.find(params[:id])
  end


  def delete
    @employee = Employee.find(params[:id])
    @employee.destroy
    redirect_to employees_url, notice: 'Employee was successfully deleted.'
  end
  private
  def employee_params
    # params.require(:employee).permit! ##permit all
    params.require(:employee).permit(:first_name,:last_name,:email,:city,:state,:country)
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @title_text = "Hello World"
    @subtitle_text = "I am learning"
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def contact_us
  end

  def pages1
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/employees/edit.html.erb
<h1 class="text-2xl font-bold mb-6">Update Employee</h1>

<%= form_with model: @employee, local: true, class: "space-y-6" do |form| %>
  <% if @employee.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold">Please fix the errors below:</strong>
      <ul class="list-disc list-inside mt-2">
        <% @employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, class: "block text-sm font-medium text-gray-700" %>
    <div class="mt-1">
      <%= form.text_field :first_name, class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>
    <% @employee.errors.full_messages_for(:first_name).each do |msg| %>
      <p class="text-red-600 text-sm mt-1"><%= msg %></p>
    <% end %>
  </div>
  
  <div>
    <%= form.label :last_name, class: "block text-sm font-medium text-gray-700" %>
    <div class="mt-1">
      <%= form.text_field :last_name, class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>
    <% @employee.errors.full_messages_for(:last_name).each do |msg| %>
      <p class="text-red-600 text-sm mt-1"><%= msg %></p>
    <% end %>
  </div>
  
  <div>
    <%= form.label :email, class: "block text-sm font-medium text-gray-700" %>
    <div class="mt-1">
      <%= form.email_field :email, class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>
    <% @employee.errors.full_messages_for(:email).each do |msg| %>
      <p class="text-red-600 text-sm mt-1"><%= msg %></p>
    <% end %>
  </div>
  
  <div>
    <%= form.label :city, class: "block text-sm font-medium text-gray-700" %>
    <div class="mt-1">
      <%= form.text_field :city, class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>
    <% @employee.errors.full_messages_for(:city).each do |msg| %>
      <p class="text-red-600 text-sm mt-1"><%= msg %></p>
    <% end %>
  </div>
  
  <div>
    <%= form.label :state, class: "block text-sm font-medium text-gray-700" %>
    <div class="mt-1">
      <%= form.text_field :state, class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>
    <% @employee.errors.full_messages_for(:state).each do |msg| %>
      <p class="text-red-600 text-sm mt-1"><%= msg %></p>
    <% end %>
  </div>
  
  <div>
    <%= form.label :country, class: "block text-sm font-medium text-gray-700" %>
    <div class="mt-1">
      <%= form.text_field :country, class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>
    <% @employee.errors.full_messages_for(:country).each do |msg| %>
      <p class="text-red-600 text-sm mt-1"><%= msg %></p>
    <% end %>
  </div>
  
  <div class="mt-6">
    <%= form.submit  class: "w-full px-4 py-2 bg-indigo-600 text-white font-medium rounded-md shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>
  
  <div class="mt-6">
    <%= link_to 'Back to employees', employees_path, class: "w-full inline-block px-4 py-2 bg-gray-400 text-white font-medium text-center rounded-md shadow-sm hover:bg-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500" %>
  </div>
<% end %>

app/views/employees/index.html.erb
<%= link_to " Create New Employee",empnew_path, class:"bg-red-500 p-1 m-5 rounded-lg"%>
<table class="min-w-full divide-y divide-gray-200">
  <thead class="bg-gray-50">
    <tr>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">First Name</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Last Name</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Email</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">City</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">State</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Country</th>
      <th class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Actions</th>
    </tr>
  </thead>
  <tbody class="bg-white divide-y divide-gray-200">
    <% @employees.each do |emp| %>
      <tr>
        <%= emp.id %>     
        <td class="px-6 py-4 whitespace-nowrap"><%= emp.first_name %></td>
        <td class="px-6 py-4 whitespace-nowrap"><%= emp.last_name %></td>
        <td class="px-6 py-4 whitespace-nowrap"><%= emp.email %></td>
        <td class="px-6 py-4 whitespace-nowrap"><%= emp.city %></td>
        <td class="px-6 py-4 whitespace-nowrap"><%= emp.state %></td>
        <td class="px-6 py-4 whitespace-nowrap"><%= emp.country %></td>
        <td class="px-6 py-4 whitespace-nowrap">
          <%= link_to "Show", employee_path(emp), class: "text-blue-600 hover:text-blue-800" %>
          <%= link_to "Edit", edit_employee_path(emp), class: "text-green-600 hover:text-green-800" %>
<li><%= link_to "Destroy", employee_path(emp), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/employees/new.html.erb
<h1 class="text-2xl font-bold mb-6">Create New Employee</h1>

<%= form_with model: @employee, local: true, class: "space-y-6" do |form| %>
  <% if @employee.errors.any? %>
    <div class="bg-red-100 border border-red-400 text-red-700 px-4 py-3 rounded relative" role="alert">
      <strong class="font-bold">Please fix the errors below:</strong>
      <ul class="list-disc list-inside mt-2">
        <% @employee.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, class: "block text-sm font-medium text-gray-700" %>
    <div class="mt-1">
      <%= form.text_field :first_name, class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>
    <% @employee.errors.full_messages_for(:first_name).each do |msg| %>
      <p class="text-red-600 text-sm mt-1"><%= msg %></p>
    <% end %>
  </div>
  
  <div>
    <%= form.label :last_name, class: "block text-sm font-medium text-gray-700" %>
    <div class="mt-1">
      <%= form.text_field :last_name, class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>
    <% @employee.errors.full_messages_for(:last_name).each do |msg| %>
      <p class="text-red-600 text-sm mt-1"><%= msg %></p>
    <% end %>
  </div>
  
  <div>
    <%= form.label :email, class: "block text-sm font-medium text-gray-700" %>
    <div class="mt-1">
      <%= form.email_field :email, class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>
    <% @employee.errors.full_messages_for(:email).each do |msg| %>
      <p class="text-red-600 text-sm mt-1"><%= msg %></p>
    <% end %>
  </div>
  
  <div>
    <%= form.label :city, class: "block text-sm font-medium text-gray-700" %>
    <div class="mt-1">
      <%= form.text_field :city, class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>
    <% @employee.errors.full_messages_for(:city).each do |msg| %>
      <p class="text-red-600 text-sm mt-1"><%= msg %></p>
    <% end %>
  </div>
  
  <div>
    <%= form.label :state, class: "block text-sm font-medium text-gray-700" %>
    <div class="mt-1">
      <%= form.text_field :state, class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>
    <% @employee.errors.full_messages_for(:state).each do |msg| %>
      <p class="text-red-600 text-sm mt-1"><%= msg %></p>
    <% end %>
  </div>
  
  <div>
    <%= form.label :country, class: "block text-sm font-medium text-gray-700" %>
    <div class="mt-1">
      <%= form.text_field :country, class: "block w-full px-3 py-2 border border-gray-300 rounded-md shadow-sm focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm" %>
    </div>
    <% @employee.errors.full_messages_for(:country).each do |msg| %>
      <p class="text-red-600 text-sm mt-1"><%= msg %></p>
    <% end %>
  </div>
  
  <div class="mt-6">
    <%= form.submit 'Create Employee', class: "w-full px-4 py-2 bg-indigo-600 text-white font-medium rounded-md shadow-sm hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500" %>
  </div>
  
  <div class="mt-6">
    <%= link_to 'Back to employees', employees_path, class: "w-full inline-block px-4 py-2 bg-gray-400 text-white font-medium text-center rounded-md shadow-sm hover:bg-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500" %>
  </div>
<% end %>

app/views/employees/show.html.erb
<h1 class="text-2xl font-bold mb-6">Employee Details</h1>

<div class="bg-white shadow overflow-hidden sm:rounded-lg">
  <div class="px-4 py-5 sm:px-6">
    <h3 class="text-lg leading-6 font-medium text-gray-900">
      Employee Information
    </h3>
    <p class="mt-1 max-w-2xl text-sm text-gray-500">
      Personal details and information.
    </p>
  </div>
  <div class="border-t border-gray-200">
    <dl>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          First Name
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @employee.first_name %>
        </dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Last Name
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @employee.last_name %>
        </dd>
      </div>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Email
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @employee.email %>
        </dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          City
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @employee.city %>
        </dd>
      </div>
      <div class="bg-gray-50 px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          State
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @employee.state %>
        </dd>
      </div>
      <div class="bg-white px-4 py-5 sm:grid sm:grid-cols-3 sm:gap-4 sm:px-6">
        <dt class="text-sm font-medium text-gray-500">
          Country
        </dt>
        <dd class="mt-1 text-sm text-gray-900 sm:mt-0 sm:col-span-2">
          <%= @employee.country %>
        </dd>
      </div>
    </dl>
  </div>
</div>

<div class="mt-6">
  <%= link_to 'Back to Employees', employees_path, class: "w-full inline-block px-4 py-2 bg-gray-400 text-white font-medium text-center rounded-md shadow-sm hover:bg-gray-500 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-gray-500" %>

</div>

app/views/home/index.html.erb
<h1 class ="bg-red-500"><%= @title_text%> </h1>

<p> <%= @subtitle_text%> </p>

<%= render 'shared/links'%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Spree2</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
      <script src="https://cdn.tailwindcss.com"></script>
<script>
    tailwind.config = {
      theme: {
        extend: {
          colors: {
            clifford: '#da373d',
          }
        }
      }
    }
  </script>
   <style type="text/tailwindcss">
    @layer utilities {
      .content-auto {
        content-visibility: auto;
      }
    }
  </style>
    <script src="https://cdn.tailwindcss.com?plugins=forms,typography,aspect-ratio,line-clamp,container-queries"></script>

  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/about_us.html.erb
<h1>Pages#about_us</h1>
<p>Find me in app/views/pages/about_us.html.erb</p>

<%= render 'shared/links'%>

app/views/pages/contact_us.html.erb
<h1>Pages#contact_us</h1>
<p>Find me in app/views/pages/contact_us.html.erb</p>
<%= render 'shared/links'%>

app/views/pages/pages1.html.erb
<h1>Pages#pages1</h1>
<p>Find me in app/views/pages/pages1.html.erb</p>
<%= render 'shared/links'%>

app/views/shared/_links.html.erb
<%= link_to 'home path', root_path, class: 'text-red-500' %>
<%= link_to 'contact us' ,contact_path, class: 'text-blue-500' %>
<%= link_to 'pages 1' ,pages1_path,class: 'text-green-500' %>
<%= link_to 'About us', about_path, class: 'text-yellow-500'%>